"""Central application identity and domain enumerations."""

from __future__ import annotations

from enum import StrEnum

APP_NAME = "CreoPDM"
APP_VERSION = "0.2.0"
APP_SCHEMA_VERSION = 1
CREO_OPEN_MODES = ("association", "embedded")
CREO_VIEW_OPEN_MODES = ("association",)
SIDEBAR_COLLAPSED_COOKIE = "creopdm_sidebar"

DEFAULT_BRANCH = "main"
DEFAULT_REVISION = "A"
INITIAL_ITERATION = 1

PROJECT_MARKER_DIR = ".creopdm"
PROJECT_JSON_NAME = "project.json"
SCHEMA_VERSION_NAME = "schema_version"

STANDARD_PROJECT_FOLDERS = ("CAD", "Documents", "Exports", "References")


class ObjectType(StrEnum):
    CREO_PART = "CREO_PART"
    CREO_ASSEMBLY = "CREO_ASSEMBLY"
    CREO_DRAWING = "CREO_DRAWING"
    CREO_MANUFACTURING = "CREO_MANUFACTURING"
    CAD = "CAD"
    STEP = "STEP"
    PDF = "PDF"
    DOCUMENT = "DOCUMENT"
    SPREADSHEET = "SPREADSHEET"
    IMAGE = "IMAGE"
    TEXT = "TEXT"
    OTHER = "OTHER"


class LifecycleState(StrEnum):
    IN_WORK = "IN_WORK"
    RELEASED = "RELEASED"
    OBSOLETE = "OBSOLETE"


class CheckoutStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RETURNED = "RETURNED"
    CANCELLED = "CANCELLED"
    STALE = "STALE"


class DependencyType(StrEnum):
    ASSEMBLY_MEMBER = "ASSEMBLY_MEMBER"
    DRAWING_MODEL = "DRAWING_MODEL"
    REFERENCE = "REFERENCE"
    SKELETON = "SKELETON"
    MERGE = "MERGE"
    UNKNOWN = "UNKNOWN"


class ActivityAction(StrEnum):
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    OBJECT_ADDED = "OBJECT_ADDED"
    OBJECT_REMOVED = "OBJECT_REMOVED"
    WORKSPACE_CLEARED = "WORKSPACE_CLEARED"
    CHECKED_OUT = "CHECKED_OUT"
    CHECKOUT_CANCELLED = "CHECKOUT_CANCELLED"
    CHECKED_IN = "CHECKED_IN"
    VERSION_RESTORED = "VERSION_RESTORED"
    REMOTE_PUSH = "REMOTE_PUSH"
    REMOTE_PULL = "REMOTE_PULL"
    STATE_CHANGED = "STATE_CHANGED"
    ERROR = "ERROR"


class RemoteMode(StrEnum):
    LOCAL_ONLY = "LOCAL_ONLY"
    LOCAL_WITH_REMOTE = "LOCAL_WITH_REMOTE"


CREO_FILE_EXTENSIONS = frozenset(
    {
        ".prt",
        ".asm",
        ".drw",
        ".mfg",
        ".frm",
        ".lay",
        ".sec",
        ".dgm",
        ".rep",
        ".mrk",
        ".int",
        ".g",
        ".cem",
    }
)

DEFAULT_CAD_MODELS_EXTENSIONS = (
    ".prt",
    ".asm",
    ".drw",
)

DEFAULT_DOCUMENT_EXTENSIONS = (
    ".pdf",
    ".xps",
    ".doc",
    ".docx",
    ".rtf",
    ".txt",
    ".odt",
    ".xls",
    ".xlsx",
    ".csv",
    ".ppt",
    ".pptx",
    ".pps",
    ".ppsx",
    ".mpp",
    ".vsd",
    ".vsdx",
    ".pub",
    ".one",
    ".html",
    ".htm",
    ".eml",
    ".msg",
    ".psd",
)

PREVIOUS_DEFAULT_DOCUMENT_SETS = (
    frozenset(
        {
            ".pdf",
            ".xps",
            ".oxps",
            ".ps",
            ".doc",
            ".docx",
            ".docm",
            ".dot",
            ".dotx",
            ".dotm",
            ".rtf",
            ".odt",
            ".ott",
            ".wpd",
            ".pages",
            ".xls",
            ".xlsx",
            ".xlsm",
            ".xlsb",
            ".xlt",
            ".xltx",
            ".xltm",
            ".ods",
            ".csv",
            ".tsv",
            ".numbers",
            ".ppt",
            ".pptx",
            ".pptm",
            ".pps",
            ".ppsx",
            ".pot",
            ".potx",
            ".odp",
            ".key",
            ".mpp",
            ".mpt",
            ".vsd",
            ".vsdx",
            ".vss",
            ".vstx",
            ".pub",
            ".one",
            ".onepkg",
            ".odg",
            ".jpg",
            ".jpeg",
            ".png",
            ".gif",
            ".bmp",
            ".tif",
            ".tiff",
            ".svg",
            ".webp",
            ".heic",
            ".ico",
            ".eps",
            ".emf",
            ".wmf",
            ".html",
            ".htm",
            ".xhtml",
            ".mhtml",
            ".css",
            ".scss",
            ".sass",
            ".less",
            ".js",
            ".mjs",
            ".cjs",
            ".jsx",
            ".ts",
            ".tsx",
            ".md",
            ".markdown",
            ".rst",
            ".adoc",
            ".txt",
            ".text",
            ".json",
            ".yaml",
            ".yml",
            ".toml",
            ".eml",
            ".msg",
            ".oft",
            ".epub",
            ".mobi",
            ".mcdx",
            ".tex",
            ".ltx",
            ".bib",
        }
    ),
    frozenset(
        {
            ".pdf",
            ".xps",
            ".doc",
            ".docx",
            ".rtf",
            ".txt",
            ".odt",
            ".xls",
            ".xlsx",
            ".csv",
            ".ppt",
            ".pptx",
            ".pps",
            ".ppsx",
            ".mpp",
            ".vsd",
            ".vsdx",
            ".pub",
            ".one",
            ".html",
            ".htm",
            ".eml",
            ".msg",
        }
    ),
)

DEFAULT_CREO_MODEL_EXTENSIONS = (
    ".prt",
    ".asm",
    ".drw",
    ".frm",
    ".mfg",
    ".lay",
    ".sec",
    ".dgm",
    ".rep",
    ".mrk",
    ".int",
    ".g",
    ".cem",
    ".apr",
    ".pvz",
    ".ol",
    ".ed",
    ".edz",
    ".pvs",
    ".stp",
    ".step",
    ".igs",
    ".iges",
    ".dxf",
    ".dwg",
    ".stl",
    ".vda",
    ".neu",
    ".ibl",
    ".pts",
    ".rwd",
    ".rwt",
    ".mrs",
    ".xdb",
    ".cgm",
    ".obj",
    ".wrl",
    ".emn",
    ".emp",
    ".icm",
    ".bdl",
    ".pkg",
    ".sdp",
    ".sda",
    ".sdac",
    ".sdpc",
    ".mi",
    ".bi",
    ".asc",
    ".sat",
    ".sab",
    ".x_t",
    ".xmt_txt",
    ".x_b",
    ".xmt_bin",
    ".x_n",
    ".xmt_neu",
    ".xmt",
    ".p_b",
    ".model",
    ".exp",
    ".session",
    ".ai",
    ".tsh",
    ".vtx",
    ".acs",
    ".ipt",
    ".iam",
    ".sldprt",
    ".sldasm",
    ".catpart",
    ".catproduct",
    ".cgr",
    ".3dm",
    ".usd",
    ".sla",
    ".par",
    ".psm",
    ".3mf",
    ".she",
)

DEFAULT_CREO_VIEW_EXTENSIONS = (
    ".pvz",
    ".pvs",
    ".ol",
    ".ed",
    ".edz",
)

OBJECT_TYPE_BY_EXTENSION: dict[str, ObjectType] = {
    ".prt": ObjectType.CREO_PART,
    ".asm": ObjectType.CREO_ASSEMBLY,
    ".drw": ObjectType.CREO_DRAWING,
    ".mfg": ObjectType.CREO_MANUFACTURING,
    ".step": ObjectType.STEP,
    ".stp": ObjectType.STEP,
    ".iges": ObjectType.STEP,
    ".igs": ObjectType.STEP,
    ".pdf": ObjectType.PDF,
    ".xps": ObjectType.PDF,
    ".oxps": ObjectType.PDF,
    ".ps": ObjectType.PDF,
    ".doc": ObjectType.DOCUMENT,
    ".docx": ObjectType.DOCUMENT,
    ".docm": ObjectType.DOCUMENT,
    ".dot": ObjectType.DOCUMENT,
    ".dotx": ObjectType.DOCUMENT,
    ".dotm": ObjectType.DOCUMENT,
    ".rtf": ObjectType.DOCUMENT,
    ".odt": ObjectType.DOCUMENT,
    ".ott": ObjectType.DOCUMENT,
    ".wpd": ObjectType.DOCUMENT,
    ".pages": ObjectType.DOCUMENT,
    ".xls": ObjectType.SPREADSHEET,
    ".xlsx": ObjectType.SPREADSHEET,
    ".xlsm": ObjectType.SPREADSHEET,
    ".xlsb": ObjectType.SPREADSHEET,
    ".xlt": ObjectType.SPREADSHEET,
    ".xltx": ObjectType.SPREADSHEET,
    ".xltm": ObjectType.SPREADSHEET,
    ".ods": ObjectType.SPREADSHEET,
    ".csv": ObjectType.SPREADSHEET,
    ".tsv": ObjectType.SPREADSHEET,
    ".numbers": ObjectType.SPREADSHEET,
    ".ppt": ObjectType.DOCUMENT,
    ".pptx": ObjectType.DOCUMENT,
    ".pptm": ObjectType.DOCUMENT,
    ".pps": ObjectType.DOCUMENT,
    ".ppsx": ObjectType.DOCUMENT,
    ".pot": ObjectType.DOCUMENT,
    ".potx": ObjectType.DOCUMENT,
    ".odp": ObjectType.DOCUMENT,
    ".key": ObjectType.DOCUMENT,
    ".mpp": ObjectType.DOCUMENT,
    ".mpt": ObjectType.DOCUMENT,
    ".vsd": ObjectType.DOCUMENT,
    ".vsdx": ObjectType.DOCUMENT,
    ".vss": ObjectType.DOCUMENT,
    ".vstx": ObjectType.DOCUMENT,
    ".pub": ObjectType.DOCUMENT,
    ".one": ObjectType.DOCUMENT,
    ".onepkg": ObjectType.DOCUMENT,
    ".odg": ObjectType.DOCUMENT,
    ".txt": ObjectType.TEXT,
    ".text": ObjectType.TEXT,
    ".md": ObjectType.TEXT,
    ".markdown": ObjectType.TEXT,
    ".rst": ObjectType.TEXT,
    ".adoc": ObjectType.TEXT,
    ".json": ObjectType.TEXT,
    ".yaml": ObjectType.TEXT,
    ".yml": ObjectType.TEXT,
    ".toml": ObjectType.TEXT,
    ".jpg": ObjectType.IMAGE,
    ".jpeg": ObjectType.IMAGE,
    ".png": ObjectType.IMAGE,
    ".gif": ObjectType.IMAGE,
    ".bmp": ObjectType.IMAGE,
    ".tif": ObjectType.IMAGE,
    ".tiff": ObjectType.IMAGE,
    ".svg": ObjectType.IMAGE,
    ".webp": ObjectType.IMAGE,
    ".heic": ObjectType.IMAGE,
    ".ico": ObjectType.IMAGE,
    ".eps": ObjectType.IMAGE,
    ".emf": ObjectType.IMAGE,
    ".wmf": ObjectType.IMAGE,
    ".psd": ObjectType.IMAGE,
    ".html": ObjectType.DOCUMENT,
    ".htm": ObjectType.DOCUMENT,
    ".xhtml": ObjectType.DOCUMENT,
    ".mhtml": ObjectType.DOCUMENT,
    ".css": ObjectType.DOCUMENT,
    ".js": ObjectType.DOCUMENT,
    ".mjs": ObjectType.DOCUMENT,
    ".cjs": ObjectType.DOCUMENT,
    ".jsx": ObjectType.DOCUMENT,
    ".ts": ObjectType.DOCUMENT,
    ".tsx": ObjectType.DOCUMENT,
    ".scss": ObjectType.DOCUMENT,
    ".sass": ObjectType.DOCUMENT,
    ".less": ObjectType.DOCUMENT,
    ".eml": ObjectType.DOCUMENT,
    ".msg": ObjectType.DOCUMENT,
    ".oft": ObjectType.DOCUMENT,
    ".epub": ObjectType.DOCUMENT,
    ".mobi": ObjectType.DOCUMENT,
    ".mcdx": ObjectType.DOCUMENT,
    ".tex": ObjectType.DOCUMENT,
    ".ltx": ObjectType.DOCUMENT,
    ".bib": ObjectType.DOCUMENT,
}

DEFAULT_FOLDER_BY_TYPE: dict[ObjectType, str] = {
    ObjectType.CREO_PART: "CAD",
    ObjectType.CREO_ASSEMBLY: "CAD",
    ObjectType.CREO_DRAWING: "CAD",
    ObjectType.CREO_MANUFACTURING: "CAD",
    ObjectType.CAD: "CAD",
    ObjectType.STEP: "Exports",
    ObjectType.PDF: "Documents",
    ObjectType.DOCUMENT: "Documents",
    ObjectType.SPREADSHEET: "Documents",
    ObjectType.IMAGE: "Documents",
    ObjectType.TEXT: "Documents",
    ObjectType.OTHER: "Documents",
}

DOCUMENT_OBJECT_TYPES = frozenset(
    {
        ObjectType.PDF,
        ObjectType.DOCUMENT,
        ObjectType.SPREADSHEET,
        ObjectType.IMAGE,
        ObjectType.TEXT,
    }
)

CAD_OBJECT_TYPES = frozenset(
    {
        ObjectType.CREO_PART,
        ObjectType.CREO_ASSEMBLY,
        ObjectType.CREO_DRAWING,
        ObjectType.CREO_MANUFACTURING,
        ObjectType.CAD,
        ObjectType.STEP,
    }
)

OTHER_OBJECT_TYPES = frozenset(item for item in ObjectType if item not in CAD_OBJECT_TYPES)

METRIC_TYPE_FILTERS: dict[str, frozenset[str] | None] = {
    "files": None,
    "creo_parts": frozenset({ObjectType.CREO_PART.value}),
    "assemblies": frozenset({ObjectType.CREO_ASSEMBLY.value}),
    "drawings": frozenset({ObjectType.CREO_DRAWING.value}),
    "documents": frozenset(item.value for item in DOCUMENT_OBJECT_TYPES),
    "other": frozenset(item.value for item in OTHER_OBJECT_TYPES),
}

DEFAULT_LFS_PATTERNS = [
    "*.prt",
    "*.prt.*",
    "*.asm",
    "*.asm.*",
    "*.drw",
    "*.drw.*",
    "*.mfg",
    "*.mfg.*",
    "*.step",
    "*.stp",
    "*.iges",
    "*.igs",
]

DEFAULT_OPENABLE_CAD_EXTENSIONS = (
    ".ncl",
    ".tap",
    ".xml",
    ".log",
    ".lst",
)

# Local agent-cache Purge workspace: only these extensions get vault floors.
DEFAULT_PURGEABLE_EXTENSIONS = (
    ".asm",
    ".dat",
    ".drw",
    ".err",
    ".frm",
    ".gph",
    ".inf",
    ".log",
    ".lsl",
    ".lst",
    ".mat",
    ".mrd",
    ".ncl",
    ".neu",
    ".prt",
    ".sec",
    ".sym",
    ".tbl",
    ".tph",
    ".txt",
    ".xml",
)

PREVIOUS_DEFAULT_PURGEABLE_SETS: tuple[frozenset[str], ...] = ()

DEFAULT_EXTRA_CAD_EXTENSIONS = (
    ".tph",
    ".inf",
    ".out",
    ".tool",
    ".crc",
    ".dat",
    ".m_p",
    ".bom",
    ".tbl",
    ".xch",
    ".sym",
    ".bin",
    ".stk",
    ".mrd",
    ".xpr",
    ".xas",
    ".mtl",
    ".eda",
    ".spro",
    ".rcp",
    ".mbx",
    ".aux",
    ".cel",
    ".edm",
    ".memb",
    ".mtn",
    ".ncd",
    ".nck",
    ".plt",
    ".ppl",
    ".ptd",
    ".shd",
    ".sit",
    ".smt",
    ".tmu",
    ".tmz",
    ".als",
    ".ref",
    ".tst",
    ".map",
    ".ers",
    ".info",
    ".cbl",
    ".con",
    ".lgh",
    ".mac",
    ".bde",
    ".bdi",
    ".bdm",
    ".ger",
    ".pls",
    ".txa",
    ".dtl",
    ".gph",
    ".scl",
    ".tpm",
)

DEFAULT_TYPE_LABELS: tuple[dict[str, str], ...] = (
    {"extension": ".prt", "label": "Part"},
    {"extension": ".asm", "label": "Assembly"},
    {"extension": ".drw", "label": "Drawing"},
    {"extension": ".ncl", "label": "CL Data"},
    {"extension": ".tap, .nc, .cnc, .gcode", "label": "G-Code"},
    {"extension": ".frm", "label": "Drawing Format"},
    {"extension": ".sec", "label": "Section"},
    {"extension": ".lay", "label": "Layout"},
    {"extension": ".mfg", "label": "Manufacturing Model"},
    {"extension": ".stp, .step", "label": "STEP Model"},
    {"extension": ".igs, .iges", "label": "IGES Model"},
    {"extension": ".stl", "label": "STL Model"},
    {"extension": ".x_t, .x_b", "label": "Parasolid Model"},
    {"extension": ".sat", "label": "ACIS Model"},
    {"extension": ".jt", "label": "JT Model"},
    {"extension": ".dxf", "label": "DXF Drawing"},
    {"extension": ".dwg", "label": "DWG Drawing"},
    {"extension": ".pdf", "label": "PDF Document"},
    {"extension": ".pvz, .pvs, .ol", "label": "Creo View package"},
    {"extension": ".log", "label": "Log file"},
    {"extension": "mc_error.log", "label": "ModelCHECK Error Log"},
    {"extension": ".bin", "label": "NC Stock Model"},
    {"extension": ".txt", "label": "Text File"},
    {"extension": ".tmp", "label": "Temp File"},
    {"extension": ".xml", "label": "XML File"},
    {"extension": "mw_settings.xml", "label": "Module Works Settings"},
    {"extension": ".idx, .xas, .xpr", "label": "Instance Accelerator"},
    {"extension": ".tool", "label": "Module Works File"},
    {"extension": ".doc, .docx", "label": "Word Document"},
    {"extension": ".xls, .xlsx", "label": "Excel Document"},
    {"extension": ".csv", "label": "CSV File"},
    {"extension": ".ppt, .pptx", "label": "PowerPoint Presentation"},
    {"extension": ".stk", "label": "Stock Model"},
    {"extension": ".dtl", "label": "Drawing Setup File"},
    {"extension": ".sym", "label": "Symbol"},
    {"extension": ".gph", "label": "UDF/Group File"},
    {"extension": ".ibl", "label": "IBL Curve Data"},
    {"extension": ".pts", "label": "Point Data File"},
    {"extension": ".scl", "label": "System Colors"},
    {"extension": ".mtl", "label": "Material File"},
    {"extension": ".mrd", "label": "Material Removal Data"},
    {"extension": ".tpm", "label": "Tool Parameters"},
    {"extension": ".tph", "label": "Toolpath"},
    {"extension": ".mbx", "label": "Toolpath"},
    {"extension": ".lst", "label": "Post-list"},
    {"extension": ".ncl.tl*", "label": "Intermediate CL File"},
    {"extension": ".aux", "label": "Auxiliary Data"},
    {"extension": ".cel", "label": "Machine Parameters"},
    {"extension": ".dat", "label": "Edit Data"},
    {"extension": ".edm", "label": "Contour Parameters"},
    {"extension": ".inf", "label": "Information"},
    {"extension": ".memb", "label": "Assembly Member"},
    {"extension": ".mtn", "label": "Tool Motion"},
    {"extension": ".ncd", "label": "CL Alias"},
    {"extension": ".nck", "label": "NC Check Image"},
    {"extension": ".plt", "label": "Plot"},
    {"extension": ".ppl", "label": "Route Sheet"},
    {"extension": ".ptd", "label": "Family Table"},
    {"extension": ".shd", "label": "Shade Display"},
    {"extension": ".sit", "label": "Site Parameters"},
    {"extension": ".smt", "label": "Punch Parameters"},
    {"extension": ".crc", "label": "Circular Reference File"},
    {"extension": ".eda", "label": "ECAD data"},
    {"extension": ".mcdx", "label": "Mathcad"},
    {"extension": ".spro", "label": "Creo Flow Analysis"},
    {"extension": ".rcp", "label": "Recipe/configuration"},
    {"extension": "reviewref.inf", "label": "Reference Info"},
    {"extension": ".zip, .rar, .7z, .tar, .gz, .tgz, .bz2, .tbz", "label": "Archive"},
    {
        "extension": ".jpg, .jpeg, .tif, .bmp, .png, .gif, .svg, .tiff, .ico, .heic, .eps, .emf, .wmf",
        "label": "Image File",
    },
    {"extension": ".html, .htm", "label": "Webpage"},
    {"extension": ".css, .scss, .sass, .less", "label": "Stylesheet"},
    {"extension": ".js, .mjs, .cjs, .jsx, .ts, .tsx", "label": "JavaScript"},
    {"extension": ".bat, .cmd, .ps1, .py", "label": "Scripts/programming"},
    {"extension": ".md", "label": "Markdown"},
    {"extension": ".json", "label": "JSON"},
    {"extension": ".mil", "label": "NC Parameters"},
    {"extension": ".txf", "label": "Cutting Tool File"},
    {"extension": ".ppr", "label": "PPrint File"},
    {"extension": ".pro, .sup", "label": "Creo Configuration"},
    {"extension": ".dmt", "label": "Appearance File"},
    {"extension": ".exe", "label": "Executable"},
    {"extension": ".rbn", "label": "Ribbon File"},
    {"extension": ".hol", "label": "Hole File"},
    {"extension": ".mcc, .mcg, .mcs, .mcq, .mcr, .mch, .mcn", "label": "ModelCHECK"},
    {"extension": ".ini", "label": "Configuration File"},
    {
        "extension": ".avi, .mpg, .mpeg, .mp4, .m4v, .mov, .wmv, .mkv, .webm, .flv, .3gp, .3g2, .mts, .m2ts, .ts, .vob, .ogv, .asf, .rm, .rmvb, .divx, .f4v, .mxf",
        "label": "Video",
    },
    {
        "extension": ".mp3, .wav, .wma, .aac, .m4a, .flac, .ogg, .oga, .opus, .aiff, .aif, .amr, .mid, .midi, .ac3, .mka, .ra, .ape, .au, .caf",
        "label": "Audio",
    },
    {"extension": ".tbl", "label": "Creo Table File"},
    {
        "extension": ".ttf, .otf, .ttc, .otc, .woff, .woff2, .eot, .pfb, .pfm, .afm, .fon, .fnt",
        "label": "Font",
    },
    {"extension": ".cfg", "label": "Tree Configuration"},
    {"extension": ".ui", "label": "UI Configuration"},
    {"extension": ".apr", "label": "Ansys Project"},
    {"extension": ".rwd, .rwt, .mrs, .xdb", "label": "Simulate Results"},
    {"extension": ".neu", "label": "Neutral Model"},
    {"extension": ".tmu, .tmz", "label": "Design Exploration Session"},
    {"extension": ".g", "label": "Granite File"},
    {"extension": ".sldprt", "label": "SOLIDWORKS Part"},
    {"extension": ".sldasm", "label": "SOLIDWORKS Assembly"},
    {"extension": ".slddrw", "label": "SOLIDWORKS Drawing"},
    {"extension": ".3mf", "label": "3MF Model"},
    {"extension": ".obj", "label": "OBJ Model"},
    {"extension": ".ipt", "label": "Inventor Part"},
    {"extension": ".iam", "label": "Inventor Assembly"},
    {"extension": ".idw", "label": "Inventor Drawing"},
    {"extension": ".par", "label": "Solid Edge Part"},
    {"extension": ".psm", "label": "Solid Edge Assembly"},
    {"extension": ".dft", "label": "Solid Edge Draft"},
    {"extension": ".rtf", "label": "Rich Text Document"},
    {"extension": ".mpp", "label": "Microsoft Project"},
    {"extension": ".trail", "label": "Trail File"},
    {"extension": "trail.txt*", "label": "Trail"},
    {"extension": ".docm, .dot, .dotx, .dotm", "label": "Word Document"},
    {"extension": ".odt, .ott, .pages, .wpd", "label": "Word Document"},
    {"extension": ".xlsm, .xlsb, .xlt, .xltx, .xltm", "label": "Excel Document"},
    {"extension": ".ods, .numbers", "label": "Excel Document"},
    {"extension": ".pptm, .pps, .ppsx, .pot, .potx", "label": "PowerPoint Presentation"},
    {"extension": ".odp, .key", "label": "PowerPoint Presentation"},
    {"extension": ".vsd, .vsdx, .vss, .vstx", "label": "Visio Drawing"},
    {"extension": ".msg, .eml, .oft", "label": "Email"},
    {"extension": ".epub, .mobi", "label": "E-book"},
    {"extension": ".xps, .oxps", "label": "XPS Document"},
    {"extension": ".ps", "label": "PostScript"},
    {"extension": ".yaml, .yml", "label": "YAML"},
    {"extension": ".toml", "label": "TOML"},
    {"extension": ".markdown, .rst, .adoc", "label": "Markdown"},
    {"extension": ".xhtml, .mhtml", "label": "Webpage"},
    {"extension": ".tsv", "label": "CSV File"},
    {"extension": ".pub", "label": "Publisher Document"},
    {"extension": ".one, .onepkg", "label": "OneNote"},
    {"extension": ".mpt", "label": "Microsoft Project"},
    {"extension": ".tex, .ltx, .bib", "label": "LaTeX"},
    {"extension": ".odg", "label": "OpenDocument Drawing"},
    {"extension": ".psd", "label": "Photoshop"},
    {"extension": ".bom", "label": "BOM"},
    {"extension": ".m_p", "label": "Mass Properties"},
    {"extension": ".wrl", "label": "VRML"},
    {"extension": ".dgm", "label": "Diagram"},
    {"extension": ".mrk", "label": "Markup"},
    {"extension": ".als", "label": "Assembly Program"},
    {"extension": ".ref", "label": "Rename Reference"},
    {"extension": ".tst", "label": "Verify Results"},
    {"extension": ".map", "label": "Color Map"},
    {"extension": ".ers", "label": "Setup Errors"},
    {"extension": ".info", "label": "Compare/Review Info"},
    {"extension": ".cbl", "label": "Cable Parameters"},
    {"extension": ".con", "label": "Connector Parameters"},
    {"extension": ".lgh", "label": "Lights"},
    {"extension": ".mac", "label": "Machine Data"},
    {"extension": ".bde", "label": "Mesh Aspect Errors"},
    {"extension": ".bdi", "label": "Mesh Jacobian Errors"},
    {"extension": ".bdm", "label": "Mesh Mid-Ratio Errors"},
    {"extension": ".ger", "label": "Geometry Errors"},
    {"extension": ".pls", "label": "Part Program"},
    {"extension": ".txa", "label": "Training"},
)

# Type-column label → icon file in static/icons/ (SVG or PNG).
# Extensions inherit icons through type_labels settings → label → file.
DEFAULT_TYPE_ICON_BY_LABEL: dict[str, str] = {
    "Part": "part.png",
    "Assembly": "assembly.png",
    "Drawing": "drawing.png",
    "PDF Document": "pdf.png",
    "XPS Document": "xps.png",
    "Word Document": "word.png",
    "Rich Text Document": "rtf.png",
    "Excel Document": "excel.png",
    "CSV File": "csv.png",
    "PowerPoint Presentation": "powerpoint.png",
    "Visio Drawing": "visio.png",
    "Microsoft Project": "project.png",
    "Publisher Document": "publisher.png",
    "OneNote": "onenote.png",
    "Webpage": "webpage.png",
    "Email": "email.png",
    "Photoshop": "photoshop.png",
    "XML File": "xml.png",
    "Log file": "log.png",
    "ModelCHECK Error Log": "log.png",
    "Text File": "text.png",
    "Stylesheet": "css.png",
    "JavaScript": "javascript.png",
    "Markdown": "markdown.png",
    "JSON": "json.png",
    "Executable": "exe.png",
    "Configuration File": "ini.png",
    "Audio": "audio.png",
    "Video": "video.png",
    "Font": "font.png",
    "SOLIDWORKS Part": "sldprt.png",
    "SOLIDWORKS Assembly": "sldasm.png",
    "SOLIDWORKS Drawing": "slddrw.png",
    "3MF Model": "model3d.png",
    "OBJ Model": "obj.png",
    "STEP Model": "step.png",
    "IGES Model": "model3d.png",
    "STL Model": "stl.png",
    "Parasolid Model": "model3d.png",
    "ACIS Model": "model3d.png",
    "JT Model": "model3d.png",
    "DXF Drawing": "dxf.png",
    "DWG Drawing": "dwg.png",
    "Image File": "image.png",
    "Archive": "archive.png",
    "Inventor Part": "model3d.png",
    "Inventor Assembly": "model3d.png",
    "Inventor Drawing": "dwg.png",
    "Solid Edge Part": "model3d.png",
    "Solid Edge Assembly": "model3d.png",
    "Solid Edge Draft": "dwg.png",
    "VRML": "model3d.png",
}

PREVIOUS_DEFAULT_TYPE_LABEL_SETS = (
    (),
)

PREVIOUS_DEFAULT_CREO_MODEL_SETS = (
    frozenset((*DEFAULT_CREO_MODEL_EXTENSIONS, ".idx", ".tmu", ".tmz")),
    frozenset((*DEFAULT_CREO_MODEL_EXTENSIONS, ".tmu", ".tmz")),
    frozenset((*DEFAULT_CREO_MODEL_EXTENSIONS, ".idx")),
)

DEFAULT_IGNORE_PATTERNS = (
    "*.tst",
    "*.err",
    "*.acl",
    "trail.txt*",
    "std.out",
    "std.err",
    "proimpex.errors",
    "regen_backup_model*.mrd.*",
    "traceback.log",
    "mapkeys.pro",
    "config.pro",
    "config.sup",
    "creo_parametric_customization.ui",
    ".exe",
)

PREVIOUS_DEFAULT_IGNORE_SETS = (
    frozenset(
        {
            "*.tst",
            "*.err",
            "*.acl",
            "trail.txt*",
            "std.out",
            "std.err",
            "proimpex.errors",
        }
    ),
    frozenset(
        {
            "*.tst",
            "*.err",
            "*.acl",
            "trail.txt*",
            "std.out",
            "std.err",
            "proimpex.errors",
            "regen_backup_model*.mrd.*",
        }
    ),
    frozenset(
        {
            "*.tst",
            "*.err",
            "*.acl",
            "trail.txt*",
            "std.out",
            "std.err",
            "proimpex.errors",
            "regen_backup_model*.mrd.*",
            "traceback.log",
            "mapkeys.pro",
            "config.pro",
            "config.sup",
            "creo_parametric_customization.ui",
        }
    ),
)

PREVIOUS_DEFAULT_EXTRA_CAD_SETS = (
    frozenset({".dxf", ".dwg", ".ncl", ".tph", ".nc", ".tap", ".cnc"}),
    frozenset(
        {
            ".ncl",
            ".dxf",
            ".tap",
            ".tph",
            ".inf",
            ".xml",
            ".out",
            ".tool",
            ".idx",
            ".log",
            ".step",
            ".stp",
            ".ipt",
            ".stl",
            ".wrl",
            ".sec",
            ".crc",
        }
    ),
    frozenset(
        {
            ".ncl",
            ".dxf",
            ".tap",
            ".tph",
            ".inf",
            ".xml",
            ".out",
            ".tool",
            ".idx",
            ".log",
            ".step",
            ".stp",
            ".ipt",
            ".stl",
            ".wrl",
            ".sec",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".igs",
            ".tbl",
            ".frm",
            ".mfg",
            ".dgm",
            ".lay",
            ".xch",
            ".sym",
        }
    ),
    frozenset(
        {
            ".ncl",
            ".dxf",
            ".tap",
            ".tph",
            ".inf",
            ".xml",
            ".out",
            ".tool",
            ".idx",
            ".log",
            ".step",
            ".stp",
            ".ipt",
            ".stl",
            ".wrl",
            ".sec",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".igs",
            ".tbl",
            ".frm",
            ".mfg",
            ".dgm",
            ".lay",
            ".xch",
            ".sym",
            ".bin",
            ".stk",
            ".mrd",
            ".xpr",
        }
    ),
    frozenset(
        {
            ".ncl",
            ".tap",
            ".tph",
            ".inf",
            ".xml",
            ".out",
            ".tool",
            ".idx",
            ".log",
            ".wrl",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".tbl",
            ".xch",
            ".sym",
            ".bin",
            ".stk",
            ".mrd",
            ".xpr",
        }
    ),
    frozenset(
        {
            ".ncl",
            ".tap",
            ".tph",
            ".inf",
            ".xml",
            ".out",
            ".tool",
            ".log",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".tbl",
            ".xch",
            ".sym",
            ".bin",
            ".stk",
            ".mrd",
            ".xpr",
        }
    ),
    frozenset(
        {
            ".ncl",
            ".tap",
            ".tph",
            ".inf",
            ".xml",
            ".out",
            ".tool",
            ".log",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".tbl",
            ".xch",
            ".sym",
            ".bin",
            ".stk",
            ".mrd",
            ".xpr",
            ".mtl",
        }
    ),
    frozenset(
        {
            ".tph",
            ".inf",
            ".out",
            ".tool",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".tbl",
            ".xch",
            ".sym",
            ".bin",
            ".stk",
            ".mrd",
            ".xpr",
            ".mtl",
        }
    ),
    frozenset(
        {
            ".tph",
            ".inf",
            ".out",
            ".tool",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".tbl",
            ".xch",
            ".sym",
            ".bin",
            ".stk",
            ".mrd",
            ".xpr",
            ".mtl",
            ".eda",
            ".spro",
        }
    ),
    frozenset(
        {
            ".tph",
            ".inf",
            ".out",
            ".tool",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".tbl",
            ".xch",
            ".sym",
            ".bin",
            ".stk",
            ".mrd",
            ".xpr",
            ".mtl",
            ".eda",
            ".spro",
            ".rcp",
        }
    ),
    frozenset(
        {
            ".tph",
            ".inf",
            ".out",
            ".tool",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".tbl",
            ".xch",
            ".sym",
            ".bin",
            ".stk",
            ".mrd",
            ".xpr",
            ".mtl",
            ".eda",
            ".spro",
            ".rcp",
            ".mbx",
        }
    ),
    frozenset(
        {
            ".tph",
            ".inf",
            ".out",
            ".tool",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".tbl",
            ".xch",
            ".sym",
            ".bin",
            ".stk",
            ".mrd",
            ".xpr",
            ".mtl",
            ".eda",
            ".spro",
            ".rcp",
            ".mbx",
            ".aux",
            ".cel",
            ".edm",
            ".memb",
            ".mtn",
            ".ncd",
            ".nck",
            ".plt",
            ".ppl",
            ".ptd",
            ".shd",
            ".sit",
            ".smt",
        }
    ),
    frozenset(
        {
            ".tph",
            ".inf",
            ".out",
            ".tool",
            ".crc",
            ".dat",
            ".m_p",
            ".bom",
            ".tbl",
            ".xch",
            ".sym",
            ".bin",
            ".stk",
            ".mrd",
            ".xpr",
            ".mtl",
            ".eda",
            ".spro",
            ".rcp",
            ".mbx",
            ".aux",
            ".cel",
            ".edm",
            ".memb",
            ".mtn",
            ".ncd",
            ".nck",
            ".plt",
            ".ppl",
            ".ptd",
            ".shd",
            ".sit",
            ".smt",
            ".tmu",
            ".tmz",
        }
    ),
    frozenset(DEFAULT_EXTRA_CAD_EXTENSIONS),
)

DEFAULT_EXTRA_CAD_EXTENSIONS = (*DEFAULT_EXTRA_CAD_EXTENSIONS, ".idx")
